name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter analyze
    - run: dart format --output=none --set-exit-if-changed .
    # Uncomment the following line when you add tests
    # - run: flutter test